services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./monitoring/alerts.yaml:/etc/prometheus/alerts.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - monitoring-network

  push-gateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    networks:
      - monitoring-network
